module MiloneLang.Program

open System

[<EntryPoint>]
let main _ =
    printfn """// Generated by milone-lang.

#include <stdio.h>

int main(void) {
    printf("Hello, world!\n");
    return 0;
}"""
    0
