# name: milone-like workflow
# on:
#   push:
#     branches:
#       - milone

# jobs:
#   build:
#     name: test
#     runs-on: ubuntu-latest
#     env:
#       DOTNET_NOLOGO: true
#       DOTNET_CLI_TELEMETRY_OPTOUT: true
#     steps:
#       - uses: actions/checkout@main

#       # https://github.com/actions/setup-dotnet
#       - uses: actions/setup-dotnet@v1
#         with:
#           # SDK Version to use; x will use the latest version of the 3.1 channel
#           dotnet-version: '3.1.x'

#       - run: ./test
