name: Update README
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: updare readme build
    runs-on: ubuntu-latest
    steps:
      - name: check out files
        uses: actions/checkout@v2
      - name: configure git
        run: 'git config user.name vain0x && git.config user.email vainzerox@gmail.com'
      - name: switch to master branch
        run: git switch master
      - name: regenerate readme
        run: cat message.txt message.txt >README.md
      - name: make commit
        run: 'git add README.md && git commit -m Build && git push origin master || :'
      - name: upload
        run: git push origin master
