name: Update README
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: update readme build
    runs-on: ubuntu-latest
    steps:
      - name: check out files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git works
        run: |
          git config user.name vain0x
          git config user.email vainzerox@gmail.com
          git fetch origin master
          git switch -c master origin/master
          git merge develop --no-ff -m "Merge branch 'develop'"
      - name: regenerate readme
        run: cat message.txt message.txt >README.md
      - name: make commit and upload
        run: 'git add README.md && git commit -m Build && git push origin master || :'
